// <auto-generated />
using System;
using CarWash.Web.Infrastructures.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarWash.Web.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Booking", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BookingAddress");

                    b.Property<int>("BookingStatus");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<int>("ItemTotal");

                    b.Property<int>("PaymentType");

                    b.Property<string>("PhoneNumber");

                    b.Property<decimal>("Price");

                    b.Property<Guid?>("ServiceId");

                    b.Property<int>("ServiceType");

                    b.Property<string>("Time");

                    b.Property<string>("Title");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid?>("UserId");

                    b.Property<string>("UserName");

                    b.Property<int>("VehicleType");

                    b.HasKey("Id");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Chat", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChatType");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.ChatUser", b =>
                {
                    b.Property<Guid?>("ChatId");

                    b.Property<Guid?>("UserId");

                    b.Property<Guid?>("UserAdminId");

                    b.Property<int>("Role");

                    b.HasKey("ChatId", "UserId", "UserAdminId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatUsers");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Comment", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsPublished");

                    b.Property<int>("Likes");

                    b.Property<bool>("LikesEnabled");

                    b.Property<bool>("MaskUser");

                    b.Property<Guid?>("ServiceId")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid?>("UserId");

                    b.Property<string>("UserName")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Contact", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("Message");

                    b.Property<string>("Name");

                    b.Property<string>("Subject");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Group", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Like", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("ServiceId")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Message", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ChatId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("MessageCount");

                    b.Property<string>("Name");

                    b.Property<string>("Text");

                    b.Property<DateTime>("Timestamp");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Rating", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsCounted");

                    b.Property<bool>("MaskUser");

                    b.Property<decimal>("Score");

                    b.Property<Guid?>("ServiceId")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Service", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BookingId");

                    b.Property<int>("Comments");

                    b.Property<bool>("CommentsEnabled");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(520);

                    b.Property<bool>("IsPublished");

                    b.Property<string>("Layout")
                        .HasMaxLength(75);

                    b.Property<int>("Likes");

                    b.Property<bool>("LikesEnabled");

                    b.Property<decimal>("Price");

                    b.Property<decimal>("Rating");

                    b.Property<bool>("RatingsEnabled");

                    b.Property<int>("ServiceType")
                        .HasMaxLength(255);

                    b.Property<bool>("Thumbnail");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Vehicle");

                    b.Property<int>("Views");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.User", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BookingsId");

                    b.Property<Guid?>("ChatId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<int>("Gender");

                    b.Property<string>("LastName");

                    b.Property<int>("LoginRetries");

                    b.Property<int>("LoginStatus");

                    b.Property<bool>("MaskUser");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("RegistrationCode");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("BookingsId");

                    b.HasIndex("ChatId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.UserGroup", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("GroupId");

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("UpdateLocation");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UserAlias");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserGroup");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.UserRole", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("Role");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.ChatUser", b =>
                {
                    b.HasOne("CarWash.Web.Infrastructures.Domain.Models.Chat", "Chat")
                        .WithMany("Users")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarWash.Web.Infrastructures.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Comment", b =>
                {
                    b.HasOne("CarWash.Web.Infrastructures.Domain.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarWash.Web.Infrastructures.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Like", b =>
                {
                    b.HasOne("CarWash.Web.Infrastructures.Domain.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarWash.Web.Infrastructures.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Message", b =>
                {
                    b.HasOne("CarWash.Web.Infrastructures.Domain.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Rating", b =>
                {
                    b.HasOne("CarWash.Web.Infrastructures.Domain.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarWash.Web.Infrastructures.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.Service", b =>
                {
                    b.HasOne("CarWash.Web.Infrastructures.Domain.Models.Booking", "Booking")
                        .WithMany("Service")
                        .HasForeignKey("BookingId");
                });

            modelBuilder.Entity("CarWash.Web.Infrastructures.Domain.Models.User", b =>
                {
                    b.HasOne("CarWash.Web.Infrastructures.Domain.Models.Booking", "Bookings")
                        .WithMany("Users")
                        .HasForeignKey("BookingsId");

                    b.HasOne("CarWash.Web.Infrastructures.Domain.Models.Chat")
                        .WithMany("User")
                        .HasForeignKey("ChatId");
                });
#pragma warning restore 612, 618
        }
    }
}
